### ISSUE TITLE
Feature Request - Themes Only

### ISSUE THREAD

**Issue by daveman918** [tagyoureit/homebridge-luxor#12]
I love how this plugin works now. I'm really interested in having only the themes show up. Could you possibly add a feature (configuration) item where we can tell the plugin to only show themes and not all the groups/lights?

Thanks so much for creating this!

**Comment by tagyoureit** [comment]
Thanks.  Appreciate the feedback.

Couldn't you just assign the groups/lights to a dummy room like "Utility Closet" and hide them?  Or is there another reason to keep them completely out of the system?

**Comment by daveman918** [comment]
I absolutely could do that. However I have some clients who are very non technical and I’m trying to minimize any confusion for them. Even a dummy room with stuff in it confuses some people. 😀

**Comment by tagyoureit** [comment]
I just pushed up 4.1.0. 

There is a checkbox to hide the groups per your request.  And also the ability to use the existing color groups instead of assigning a new color for Home/Homebridge for ZDC lights.

![2021-12-10_14-00-22](https://user-images.githubusercontent.com/1646840/145646998-c959991e-cf70-4ed4-a4bf-ea36ac8d9ed6.png)

**Comment by daveman918** [comment]
Works GREAT! Thanks for making these changes!
